# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'CNAME']


# Site Settings
title: "SlackScrape"
email: "hello@slackscrape.com"
description: "Get all the emails from Slack using SlackScrape extension"
baseurl: ""
url: "https://slackscrape.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-83415340-1"
googleAnalyticsSiteUrl: "slackscrape.com"
siteVerification: "Cf0D89hO1K8t-5zE7KQ6ux2Jaix2Wlve7cyiJ-J9src"

# Head
metaKeywords: "slack, Emails, Names, Phone Nos, Skype IDs"
twitterAccount: "@slackscrape"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#features", text: "Features"}
 - {permalink: "/#blog", text: "Blog"}
 - {permalink: "/#subscribe", text: "Subscribe"}
 - {permalink: "/#pricing", text: "Pricing"}
#  - {permalink: "/#working", text: "How it works"}
bottomNavigationLinks:
 - {link: "https://chrome.google.com/webstore/detail/slack-scrape/loohaedlfkajioibocdedelgfhdenhdg", text: "Add to Chrome"}
rightNavigationButtons:
 - {link: "https://chrome.google.com/webstore/detail/slack-scrape/loohaedlfkajioibocdedelgfhdenhdg", text: "Add to Chrome"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Get loads of Emails from Slack, <typeout> for free"
eventDate: "Grow your customers base for free now!"
typeoutTextValues: '"", "Names", "Phone Nos", "Skype IDs"'
typeoutFallback: "Names"
heroButtons:
 - {link: "https://chrome.google.com/webstore/detail/slack-scrape/loohaedlfkajioibocdedelgfhdenhdg", text: "Add to Chrome"}
 - {permalink: "/#pricing", text: "Pricing"}

# About Block
aboutTitle: "Features"
aboutBlock:
 - {title: "Emails", image: "email.jpg", text: "Thousands of your prospective customer's emails can be accessed from various slack groups." }
 - {title: "Export", image: "export.jpg", text: "You can export Emails, Names, Phone Nos, Skype IDs into CSV formats for your CRMs" }
 - {title: "Target", image: "target.jpg", text: "Target the right segment of potential customers by looking at their slack group relevance" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1", specialCharacter: "M+", info: "users", detail: "for slack"}
 - {count: "500", specialCharacter: "K+", info: "emails", detail: "from your country and beyond"}
 - {count: "1", specialCharacter: "K+", info: "groups", detail: "with significant interaction"}
 - {count: "100", specialCharacter: "K+", info: "customers", detail: "from potential groups"}

# Blog Block
latestNewsTitle: "Blog"

# Venue Block
# venueBlockTitle: "How it works"
# venueTitle: "Install the extension"
# venueFeatures: ["Login using a browser window", "Scan Top 100 mails.", "Export CSV file or copy contacts to your clipboard."]

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Join our affiliate program"
subscribeAction: "https:////slackscrape.us14.list-manage.com/subscribe/post?u=2b5ad2f387fd311c8881b5c68&amp;id=f52289a81a"
subscribeInfo: "Earn 20% lifetime reward for referring customers. Your unique referral link will be sent in 12 hrs."

# Tickets Block
ticketsTitle: "Pricing"
ticketsInfo: "Your potential customers are out there and we help you reach them real quick, buy the Ultimate if you want scale real quick."
ticketsOffers:
 -
  name: "Free"
  price: "0.00"
  priceCurrency: "$"
  ribbon: "Free"
  buyButtonText: "Add to Chrome"
  ticketContentList: ["Works on any Slack Group", "100 emails per group"]
 -
  name: "Pro"
  price: "<strike>29</strike> 9.99"
  priceCurrency: "$"
  ribbon: "-66%"
  featured: true
  buyButtonLink: "https://gum.co/wZce"
  buyButtonText: "Buy Now"
  ticketContentList: ["Works on any Slack Group", "Unlimited emails upto 10 groups"]
 -
  name: "Ultimate"
  price: "49.99"
  priceCurrency: "$"
  buyButtonLink: "https://gum.co/WnVrA"
  buyButtonText: "Buy Now"
  ticketContentList: ["Works on any Slack Group", "Unlimited emails for Unlimited groups"]

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/115892416243877019965", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=slackscrape", icon: "twitter"}
 - {link: "https://facebook.com/SlackScrape-1754938191439096", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://slackscrape.com", text: "SlackScrape.com"}
   - {link: "https://slack.com", text: "Slack"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:hello@slackscrape.com", text: "hello@slackscrape.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}
   - {permalink: "/tac/", text: "Terms & Conditions"}
   - {permalink: "/pp/", text: "Privacy Policy"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "slackscrape"
